apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: dduda261/user-service:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          env:
            - name: BASE_URL
              value: "http://petdopt.local"
          envFrom:
            - configMapRef:
                name: petdopt-config
            - secretRef:
                name: petdopt-secret
          volumeMounts:
            - mountPath: /uploads
              name: user-uploads
      volumes:
        - name: user-uploads
          persistentVolumeClaim:
            claimName: user-uploads
